# Use postgres/example user/password credentials
version: '3.1'

services:
  
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - /Users/oleg/data/postgres:/var/lib/postgresql/data
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /Users/oleg/data/mongo:/data/db
    ports:
      - 27017:27017
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080


#   web:
#    image: filliny1/diplomamarketbackend:latest
#    restart: always
#    environment:
#      ASPNETCORE_ENVIRONMENT: "Development"
#    volumes:
#      - C:\Users\oleg\files:/app/files/
#    ports:
#      - "80:80"
#      - "443:443"